---
lessonName: Network Automation with Salt
lessonId: 30
category: tools
lessondiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/lesson-30/salt.png
tier: prod
prereqs:
  - 22  # Python
  - 23  # Linux
description: Salt is a powerful automation platform, and is one of the most popular choices in the world of network automation. We'll cover the basics of Salt in this lesson, and explore how to interact with our network devices using this framework.
slug: Salt
tags:
- event driven automation
- network automation
- salt
- saltstack

utilities:
- name: salt1
  image: shwetak02/salt
  ports: [22]

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
  ports: [8080, 830]

connections:
- a: vqfx1
  b: salt1

stages:
  - id: 1
    description: Salt Master and Minion

  - id: 2
    description: Junos Proxy Minions

  - id: 3
    description: Executing Junos commands in Salt

  - id: 4
    description: Junos Configuration Management with Salt
